version: '3.4'

services:
  pgcopydb:
    image: asabhi6776/pgcopydb:latest
    container_name: pgcopydb
    environment:
      - PGCOPYDB_SOURCE_PGURI='port=5432 hostsource_pg_ip dbname=dbname user=username password=password'
      - PGCOPYDB_TARGET_PGURI='port=5432 host=destination_pg_ip dbname=dbname user=username password=password'
